name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
      - name: Audit
        run: npm audit
