name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        node: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm
        run: npm i npm -g
      - name: Audit
        run: npm audit
