name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version-file: '.node-version'
      - name: Audit
        run: npm audit
