name: Test
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        node: [10, 12, 14]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm
        run: npm i npm -g
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
